name: run eslint before every push or pull request

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ci:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install 
    - run: npm i
    - run: npm ci
    - run: npm run build
    - run: npm run build --if-present
    - run: cd client && npm run lint
